services:
  - type: web
    name: qarrib
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: OWNER_INSTAPAY_NUMBER
        value: "01150209401"
      - key: CLIENT_URL
        value: "https://far3oon1.github.io/qarrib"
