services:
  - type: web
    name: qarrib
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: OWNER_INSTAPAY_NUMBER
        value: "01150209401"
      - key: MONGODB_URI
        sync: true
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: ADMIN_DEFAULT_EMAIL
        value: admin@qarrab.com
      - key: ADMIN_DEFAULT_PASSWORD
        generateValue: true
      - key: ADMIN_SECRET_KEY
        generateValue: true
      - key: CLIENT_URL
        value: "https://far3oon1.github.io/qarrib"
